services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5


  discordbot:
    build: .
    container_name: discordbot
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:password@mongodb:27017/ahribot
      SPRING_DEVTOOLS_ADD_PROPERTIES: "false"
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb_data:
